#!/bin/sh

DOMAIN="$1"
CN="$2"
PORTS="$3"
RELOAD_CMD="$4"

FRESHCERTS_HOST="localhost:9292"
KEYS_DIRECTORY="tmp"
KEY_PATH="${KEYS_DIRECTORY}/${DOMAIN}.key.pem"

curl -f "${FRESHCERTS_HOST}/v1/cert/${DOMAIN}/should_reissue" 2>/dev/null && \
	openssl genrsa -out "$KEY_PATH" 2048 2>/dev/null && \
	openssl req -new -batch -subj "$CN" -key "$KEY_PATH" -out /dev/stdout | \
	curl -s -X POST "${FRESHCERTS_HOST}/v1/cert/${DOMAIN}/issue" -F "csr=@-" -F "ports=$PORTS" -F "domain=$DOMAIN" | \
	tar -C "$KEYS_DIRECTORY" -xf - && \
	sh -c "$RELOAD_CMD"
