source 'https://rubygems.org'

gem 'puma'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'erubis'
gem 'rack-attack', '4.3.1'
gem 'activesupport'
gem 'thread_safe'
gem 'acme-client'
gem 'mail'
gem 'domain_name'
gem 'json-jwt'
gem 'psych'
